using System.Security.Claims;using DBM.POS.Domain.Entities;using DBM.POS.Infrastructure.Data;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace DBM.POS.API.Controllers;
[ApiController,Authorize,Route("api/organization/branch-servers")]
public class BranchServerController:ControllerBase{private readonly POSDbContext _db;public BranchServerController(POSDbContext db)=>_db=db;private Guid C=>Guid.Parse(User.FindFirstValue("companyId")!);
[HttpGet]public async Task<IActionResult>Get()=>Ok(await _db.BranchServers.AsNoTracking().Where(x=>x.CompanyId==C).ToListAsync());
[HttpPost]public async Task<IActionResult>Create(RequestDto r){if(!await _db.Branches.AnyAsync(x=>x.Id==r.BranchId&&x.CompanyId==C))return BadRequest(new{message="Invalid branch."});if(await _db.BranchServers.AnyAsync(x=>x.CompanyId==C&&x.BranchId==r.BranchId&&x.ServerCode==r.ServerCode))return Conflict(new{message="Server code exists."});var s=new BranchServer{CompanyId=C,BranchId=r.BranchId,ServerCode=r.ServerCode,ServerName=r.ServerName,MachineName=r.MachineName,LocalIpAddress=r.LocalIpAddress,ApiPort=r.ApiPort,SoftwareVersion=r.SoftwareVersion};_db.BranchServers.Add(s);await _db.SaveChangesAsync();return Ok(s);}
[HttpPut("{id:guid}")]public async Task<IActionResult>Update(Guid id,RequestDto r){var s=await _db.BranchServers.FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id);if(s==null)return NotFound();s.ServerName=r.ServerName;s.MachineName=r.MachineName;s.LocalIpAddress=r.LocalIpAddress;s.ApiPort=r.ApiPort;s.SoftwareVersion=r.SoftwareVersion;s.UpdatedAt=DateTime.UtcNow;await _db.SaveChangesAsync();return Ok(s);}
[HttpPost("{id:guid}/heartbeat")]public async Task<IActionResult>Heartbeat(Guid id){var s=await _db.BranchServers.FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id);if(s==null)return NotFound();s.LastSeenAt=DateTime.UtcNow;s.UpdatedAt=DateTime.UtcNow;await _db.SaveChangesAsync();return Ok(new{status="Online",lastSeenAt=s.LastSeenAt});}
public record RequestDto(Guid BranchId,string ServerCode,string ServerName,string? MachineName=null,string? LocalIpAddress=null,int ApiPort=5000,string? SoftwareVersion=null);}
