using System.Security.Claims;using DBM.POS.Domain.Entities;using DBM.POS.Infrastructure.Data;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace DBM.POS.API.Controllers;
[ApiController,Authorize,Route("api/organization/pos-devices")]
public class PosDeviceController:ControllerBase{private readonly POSDbContext _db;public PosDeviceController(POSDbContext db)=>_db=db;private Guid C=>Guid.Parse(User.FindFirstValue("companyId")!);
[HttpGet]public async Task<IActionResult>Get()=>Ok(await _db.PosDevices.AsNoTracking().Where(x=>x.CompanyId==C).Select(x=>new{x.Id,x.DeviceCode,x.DeviceName,x.TerminalNumber,x.BranchId,x.WarehouseId,x.ServerId,x.MacAddress,x.LastSeenAt,x.IsActive}).ToListAsync());
[HttpGet("{id:guid}")]public async Task<IActionResult>Get(Guid id)=>Ok(await _db.PosDevices.AsNoTracking().FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id));
[HttpPost]public async Task<IActionResult>Create(RequestDto r){if(!await _db.Branches.AnyAsync(x=>x.Id==r.BranchId&&x.CompanyId==C))return BadRequest(new{message="Invalid branch."});if(!await _db.BranchServers.AnyAsync(x=>x.Id==r.ServerId&&x.CompanyId==C&&x.BranchId==r.BranchId))return BadRequest(new{message="Invalid branch server."});if(await _db.PosDevices.AnyAsync(x=>x.CompanyId==C&&x.BranchId==r.BranchId&&x.DeviceCode==r.DeviceCode))return Conflict(new{message="Device code exists."});var d=new PosDevice{CompanyId=C,BranchId=r.BranchId,WarehouseId=r.WarehouseId,ServerId=r.ServerId,DeviceCode=r.DeviceCode,DeviceName=r.DeviceName,TerminalNumber=r.TerminalNumber,MacAddress=r.MacAddress};_db.PosDevices.Add(d);await _db.SaveChangesAsync();return Ok(d);}
[HttpPut("{id:guid}")]public async Task<IActionResult>Update(Guid id,RequestDto r){var d=await _db.PosDevices.FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id);if(d==null)return NotFound();d.DeviceCode=r.DeviceCode;d.DeviceName=r.DeviceName;d.TerminalNumber=r.TerminalNumber;d.WarehouseId=r.WarehouseId;d.ServerId=r.ServerId;d.MacAddress=r.MacAddress;d.UpdatedAt=DateTime.UtcNow;await _db.SaveChangesAsync();return Ok(d);}
[HttpPatch("{id:guid}/status")]public async Task<IActionResult>Status(Guid id,[FromBody]StatusRequest r){var d=await _db.PosDevices.FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id);if(d==null)return NotFound();d.IsActive=r.IsActive;d.UpdatedAt=DateTime.UtcNow;await _db.SaveChangesAsync();return Ok(d);}public record RequestDto(Guid BranchId,Guid ServerId,string DeviceCode,string DeviceName,int TerminalNumber,Guid? WarehouseId=null,string? MacAddress=null);public record StatusRequest(bool IsActive);}
