using System.Security.Claims;using DBM.POS.Domain.Entities;using DBM.POS.Infrastructure.Data;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace DBM.POS.API.Controllers;
[ApiController,Authorize,Route("api/pos/sessions")]
public class PosSessionController:ControllerBase{private readonly POSDbContext _db;public PosSessionController(POSDbContext db)=>_db=db;private Guid C=>Guid.Parse(User.FindFirstValue("companyId")!);private Guid U=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
[HttpGet("current")]public async Task<IActionResult>Current([FromQuery]Guid branchId,[FromQuery]Guid? posDeviceId){var q=_db.PosSessions.Where(x=>x.CompanyId==C&&x.BranchId==branchId&&x.Status=="Open");if(posDeviceId.HasValue)q=q.Where(x=>x.PosDeviceId==posDeviceId);return Ok(await q.OrderByDescending(x=>x.OpenedAt).FirstOrDefaultAsync());}
[HttpGet("{id:guid}")]public async Task<IActionResult>Get(Guid id)=>Ok(await _db.PosSessions.AsNoTracking().FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id));
[HttpPost("open")]public async Task<IActionResult>Open(OpenRequest r){if(await _db.PosSessions.AnyAsync(x=>x.CompanyId==C&&x.BranchId==r.BranchId&&x.PosDeviceId==r.PosDeviceId&&x.Status=="Open"))return Conflict(new{message="An open POS session already exists."});var s=new PosSession{CompanyId=C,BranchId=r.BranchId,WarehouseId=r.WarehouseId,PosDeviceId=r.PosDeviceId,OpenedBy=U,OpeningCash=r.OpeningCash};_db.PosSessions.Add(s);await _db.SaveChangesAsync();return Ok(s);}
[HttpPost("{id:guid}/close")]public async Task<IActionResult>Close(Guid id,CloseRequest r){var s=await _db.PosSessions.FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id&&x.Status=="Open");if(s==null)return NotFound();s.ActualCash=r.ActualCash;s.ExpectedCash=s.OpeningCash+s.CashSales+s.CashIn-s.CashOut-s.CashRefund;s.Difference=s.ActualCash-s.ExpectedCash;s.ClosedBy=U;s.ClosedAt=DateTime.UtcNow;s.Status="Closed";s.UpdatedAt=DateTime.UtcNow;await _db.SaveChangesAsync();return Ok(s);}
public record OpenRequest(Guid BranchId,Guid? WarehouseId,Guid? PosDeviceId,decimal OpeningCash);public record CloseRequest(decimal ActualCash);}
