using System.Security.Claims;using DBM.POS.Infrastructure.Data;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace DBM.POS.API.Controllers;
[ApiController,Authorize,Route("api/reports")]
public class ReportsController:ControllerBase{private readonly POSDbContext _db;public ReportsController(POSDbContext db)=>_db=db;private Guid C=>Guid.Parse(User.FindFirstValue("companyId")!);
[HttpGet("sales-summary")]public async Task<IActionResult>SalesSummary([FromQuery]DateTime?from,[FromQuery]DateTime?to,[FromQuery]Guid?branchId){var f=from?.Date??DateTime.UtcNow.Date;var t=to?.Date.AddDays(1)??f.AddDays(1);var q=_db.Sales.AsNoTracking().Where(x=>x.CompanyId==C&&x.SaleDate>=f&&x.SaleDate<t);if(branchId.HasValue)q=q.Where(x=>x.BranchId==branchId);return Ok(new{from=f,to=t,invoiceCount=await q.CountAsync(),grossSales=await q.SumAsync(x=>(decimal?)x.GrandTotal)??0,discount=await q.SumAsync(x=>(decimal?)x.Discount)??0,tax=await q.SumAsync(x=>(decimal?)x.Tax)??0,paid=await q.SumAsync(x=>(decimal?)x.PaidAmount)??0,due=await q.SumAsync(x=>(decimal?)x.DueAmount)??0});}
[HttpGet("purchase-summary")]public async Task<IActionResult>PurchaseSummary([FromQuery]DateTime?from,[FromQuery]DateTime?to,[FromQuery]Guid?branchId){var f=from?.Date??DateTime.UtcNow.Date;var t=to?.Date.AddDays(1)??f.AddDays(1);var q=_db.Purchases.AsNoTracking().Where(x=>x.CompanyId==C&&x.PurchaseDate>=f&&x.PurchaseDate<t);if(branchId.HasValue)q=q.Where(x=>x.BranchId==branchId);return Ok(new{from=f,to=t,purchaseCount=await q.CountAsync(),grandTotal=await q.SumAsync(x=>(decimal?)x.GrandTotal)??0,paid=await q.SumAsync(x=>(decimal?)x.PaidAmount)??0,due=await q.SumAsync(x=>(decimal?)x.DueAmount)??0});}
[HttpGet("stock-value")]public async Task<IActionResult>StockValue([FromQuery]Guid?warehouseId){var q=_db.StockBalances.AsNoTracking().Where(x=>x.CompanyId==C);if(warehouseId.HasValue)q=q.Where(x=>x.WarehouseId==warehouseId);return Ok(new{stockValue=await q.SumAsync(x=>(decimal?)x.Quantity*x.AverageCost)??0,items=await q.SumAsync(x=>(decimal?)x.Quantity)??0});}
[HttpGet("low-stock")]public async Task<IActionResult>LowStock([FromQuery]Guid?warehouseId){var q=_db.StockBalances.AsNoTracking().Include(x=>x.Product).Where(x=>x.CompanyId==C&&x.Product.MinStockLevel>0&&x.Quantity<=x.Product.MinStockLevel);if(warehouseId.HasValue)q=q.Where(x=>x.WarehouseId==warehouseId);return Ok(await q.Select(x=>new{x.WarehouseId,x.ProductId,x.Product.ProductCode,x.Product.ProductName,x.Quantity,x.Product.MinStockLevel}).ToListAsync());}
[HttpGet("profit")]public async Task<IActionResult>Profit([FromQuery]DateTime?from,[FromQuery]DateTime?to){var f=from?.Date??DateTime.UtcNow.Date;var t=to?.Date.AddDays(1)??f.AddDays(1);var q=_db.SaleItems.AsNoTracking().Where(x=>x.Sale.CompanyId==C&&x.Sale.SaleDate>=f&&x.Sale.SaleDate<t);var revenue=await q.SumAsync(x=>(decimal?)x.LineTotal)??0;var cost=await q.SumAsync(x=>(decimal?)x.Quantity*x.UnitCost)??0;var expenses=await _db.Expenses.Where(x=>x.CompanyId==C&&x.ExpenseDate>=f&&x.ExpenseDate<t).SumAsync(x=>(decimal?)x.Amount)??0;return Ok(new{from=f,to=t,revenue,cost,grossProfit=revenue-cost,expenses,netProfit=revenue-cost-expenses});}
}
