using System.Security.Claims; using DBM.POS.API.Services; using DBM.POS.Domain.Entities; using DBM.POS.Infrastructure.Data; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace DBM.POS.API.Controllers;
[ApiController,Authorize,Route("api/suppliers")]
public class SupplierController:ControllerBase
{private readonly POSDbContext _db;private readonly LedgerService _ledger;public SupplierController(POSDbContext db,LedgerService ledger){_db=db;_ledger=ledger;}private Guid C=>Guid.Parse(User.FindFirstValue("companyId")!);private Guid? U=>Guid.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id)?id:(Guid?)null;
[HttpGet]public async Task<IActionResult> GetAll([FromQuery]string? search,[FromQuery]bool? active){var q=_db.Suppliers.AsNoTracking().Where(x=>x.CompanyId==C);if(active.HasValue)q=q.Where(x=>x.IsActive==active);if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.SupplierCode.Contains(search)||x.SupplierName.Contains(search)||(x.Phone!=null&&x.Phone.Contains(search)));return Ok(await q.OrderBy(x=>x.SupplierName).ToListAsync());}
[HttpGet("{id:guid}")]public async Task<IActionResult> Get(Guid id){var s=await _db.Suppliers.AsNoTracking().FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id);if(s==null)return NotFound();var due=await _ledger.SupplierBalance(C,id);return Ok(new{s.Id,s.SupplierCode,s.SupplierName,s.Phone,s.Email,s.Address,s.OpeningDue,s.IsActive,currentDue=due});}
[HttpPost]public async Task<IActionResult>Create(RequestDto r){if(string.IsNullOrWhiteSpace(r.Code)||string.IsNullOrWhiteSpace(r.Name))return BadRequest(new{message="Code and name are required."});if(await _db.Suppliers.AnyAsync(x=>x.CompanyId==C&&x.SupplierCode==r.Code))return Conflict(new{message="Supplier code exists."});var s=new Supplier{CompanyId=C,SupplierCode=r.Code.Trim(),SupplierName=r.Name.Trim(),Phone=r.Phone,Email=r.Email,Address=r.Address,OpeningDue=r.OpeningDue};_db.Suppliers.Add(s);await _db.SaveChangesAsync();if(s.OpeningDue>0){await _ledger.AddSupplier(C,s.Id,null,"Opening",s.Id,s.SupplierCode,s.OpeningDue,0,"Opening payable",U);await _db.SaveChangesAsync();}return Ok(s);}
[HttpPut("{id:guid}")]public async Task<IActionResult>Update(Guid id,RequestDto r){var s=await _db.Suppliers.FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id);if(s==null)return NotFound();s.SupplierCode=r.Code.Trim();s.SupplierName=r.Name.Trim();s.Phone=r.Phone;s.Email=r.Email;s.Address=r.Address;s.UpdatedAt=DateTime.UtcNow;await _db.SaveChangesAsync();return Ok(s);}
[HttpPatch("{id:guid}/status")]public async Task<IActionResult>Status(Guid id,[FromBody]StatusRequest r){var s=await _db.Suppliers.FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id);if(s==null)return NotFound();s.IsActive=r.IsActive;s.UpdatedAt=DateTime.UtcNow;await _db.SaveChangesAsync();return Ok(s);}
[HttpDelete("{id:guid}")]public async Task<IActionResult>Delete(Guid id){var s=await _db.Suppliers.FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id);if(s==null)return NotFound();var due=await _ledger.SupplierBalance(C,id);if(due>0)return Conflict(new{message="Supplier has outstanding payable."});s.IsActive=false;s.UpdatedAt=DateTime.UtcNow;await _db.SaveChangesAsync();return Ok(new{message="Supplier deactivated"});}
[HttpGet("{id:guid}/ledger")]public async Task<IActionResult>Ledger(Guid id)=>Ok(await _db.SupplierLedgers.AsNoTracking().Where(x=>x.CompanyId==C&&x.SupplierId==id).OrderBy(x=>x.TransactionDate).ThenBy(x=>x.CreatedAt).ToListAsync());
[HttpGet("{id:guid}/purchases")]public async Task<IActionResult>Purchases(Guid id)=>Ok(await _db.Purchases.AsNoTracking().Where(x=>x.CompanyId==C&&x.SupplierId==id).OrderByDescending(x=>x.PurchaseDate).Select(x=>new{x.Id,x.PurchaseNo,x.PurchaseDate,x.GrandTotal,x.PaidAmount,x.DueAmount}).ToListAsync());
[HttpGet("{id:guid}/due")]public async Task<IActionResult>Due(Guid id){var s=await _db.Suppliers.FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id);if(s==null)return NotFound();return Ok(new{supplierId=id,currentDue=await _ledger.SupplierBalance(C,id)});}
[HttpPost("{id:guid}/payments")]public async Task<IActionResult>Payment(Guid id,PayRequest r){if(r.Amount<=0)return BadRequest(new{message="Amount must be greater than zero."});var s=await _db.Suppliers.FirstOrDefaultAsync(x=>x.CompanyId==C&&x.Id==id&&x.IsActive);if(s==null)return NotFound();var due=await _ledger.SupplierBalance(C,id);if(r.Amount>due)return BadRequest(new{message=$"Payment exceeds payable. Current due: {due}"});await _ledger.AddSupplier(C,id,r.BranchId,"Payment",null,r.ReferenceNo,0,r.Amount,r.Notes,U);await _db.SaveChangesAsync();return Ok(new{message="Supplier payment recorded",amount=r.Amount,currentDue=due-r.Amount});}
public record RequestDto(string Code,string Name,string? Phone=null,string? Email=null,string? Address=null,decimal OpeningDue=0);public record StatusRequest(bool IsActive);public record PayRequest(decimal Amount,string PaymentMethod="Cash",string? ReferenceNo=null,string? Notes=null,Guid? BranchId=null);}
