export const menu=[
{label:"Dashboard",icon:"▦",path:"/"},
{label:"Sales",icon:"▣",children:[
{label:"POS Sales",children:[{label:"New Invoice",path:"/pos"},{label:"New Invoice V2 - Mobile",path:"/pos?mobile=1"},{label:"Manage Invoices",path:"/sales"}]},
{label:"Sales",children:[{label:"New Invoice",path:"/pos"},{label:"Manage Invoices",path:"/sales"}]},
{label:"Quotes",children:[{label:"New Quote",path:"/workspace/quotes/new"},{label:"Manage Quotes",path:"/workspace/quotes"}]},
{label:"Subscriptions",children:[{label:"New Subscription",path:"/workspace/subscriptions/new"},{label:"Subscriptions",path:"/workspace/subscriptions"}]},
{label:"Credit Notes",path:"/workspace/credit-notes"}]},
{label:"Stock",icon:"▤",children:[
{label:"Items Manager",children:[{label:"New Product",path:"/products/new"},{label:"Manage Products",path:"/products"}]},
{label:"Product Categories",path:"/masters/categories"},{label:"Stock Inventory",path:"/inventory"},{label:"Stock Adjustment",path:"/inventory?mode=adjust"},{label:"Branches",path:"/organization/branches"},{label:"Warehouses",path:"/organization/warehouses"},{label:"Stock Transfer",path:"/transfers"},
{label:"Purchase Order",children:[{label:"New Order",path:"/purchases/new"},{label:"Manage Orders",path:"/purchases"}]},
{label:"Stock Return",children:[{label:"Sales Return",path:"/returns/customers"},{label:"Suppliers Records",path:"/returns/suppliers"}]},
{label:"Suppliers",children:[{label:"New Supplier",path:"/suppliers/new"},{label:"Manage Suppliers",path:"/suppliers"}]},
{label:"Products Label",children:[{label:"Custom Label",path:"/workspace/labels/custom"},{label:"Standard Label",path:"/workspace/labels/standard"}]}]},
{label:"CRM",icon:"◎",children:[
{label:"Clients",children:[{label:"New Client",path:"/customers/new"},{label:"Manage Clients",path:"/customers"}]},
{label:"Client Groups",path:"/workspace/client-groups"},{label:"Support Tickets",children:[{label:"UnSolved",path:"/workspace/tickets/unsolved"},{label:"Manage Tickets",path:"/workspace/tickets"}]}]},
{label:"Project",icon:"◇",children:[{label:"Project Management",children:[{label:"New Project",path:"/workspace/projects/new"},{label:"Manage Projects",path:"/workspace/projects"}]},{label:"To Do List",path:"/workspace/todo"}]},
{label:"Accounts",icon:"৳",children:[{label:"Accounts",children:[{label:"Manage Accounts",path:"/workspace/accounts"},{label:"BalanceSheet",path:"/workspace/balance-sheet"},{label:"Account Statements",path:"/workspace/account-statements"}]},{label:"Transactions",children:[{label:"View Transactions",path:"/workspace/transactions"},{label:"New Transaction",path:"/workspace/transactions/new"},{label:"New Transfer",path:"/workspace/transactions/transfer"},{label:"Income",path:"/expenses?type=income"},{label:"Expense",path:"/expenses"},{label:"Clients Transactions",path:"/workspace/client-transactions"}]},{label:"Income",path:"/expenses?type=income"},{label:"Expense",path:"/expenses"}]},
{label:"Promo Codes",icon:"%",children:[{label:"Coupons",children:[{label:"New Promo",path:"/workspace/coupons/new"},{label:"Manage Promo",path:"/workspace/coupons"}]}]},
{label:"Data & Reports",icon:"◫",children:[{label:"Business Registers",path:"/reports"},{label:"Statements",children:[{label:"Account Statements",path:"/workspace/account-statements"},{label:"Customer Account Statements",path:"/reports/customer-statements"},{label:"Supplier Account Statements",path:"/reports/supplier-statements"},{label:"TAX Statements",path:"/reports/tax"},{label:"Product Sales Reports",path:"/reports/product-sales"}]},{label:"Graphical Reports",children:[{label:"Product Categories",path:"/reports/categories"},{label:"Trending Products",path:"/reports/trending"},{label:"Profit",path:"/reports/profit"},{label:"Top Customers",path:"/reports/customers"},{label:"Income vs Expenses",path:"/reports/income-expense"},{label:"Income",path:"/reports/income"},{label:"Expenses",path:"/reports/expenses"}]},{label:"Summary & Report",children:[{label:"Statistics",path:"/reports"},{label:"Profit",path:"/reports/profit"},{label:"Calculate Income",path:"/reports/income"},{label:"Calculate Expenses",path:"/reports/expenses"},{label:"Sales",path:"/reports/sales"},{label:"Products",path:"/reports/products"},{label:"Employee Commission",path:"/workspace/commission"}]}]},
{label:"Miscellaneous",icon:"⋮",children:[{label:"Notes",path:"/workspace/notes"},{label:"Calendar",path:"/workspace/calendar"},{label:"Documents",path:"/workspace/documents"}]},
{label:"HRM",icon:"♙",children:[{label:"Employees",children:[{label:"Employees",path:"/workspace/employees"},{label:"Permissions",path:"/workspace/permissions"},{label:"Salaries",path:"/workspace/salaries"},{label:"Attendance",path:"/workspace/attendance"},{label:"Holidays",path:"/workspace/holidays"}]},{label:"Departments",path:"/workspace/departments"},{label:"Payroll",path:"/workspace/payroll"}]},
{label:"Data Export Import",icon:"⇄",children:[{label:"Export People Data",path:"/workspace/export-people"},{label:"Export Transactions",path:"/workspace/export-transactions"},{label:"Export Products",path:"/workspace/export-products"},{label:"Account Statements",path:"/workspace/export-accounts"},{label:"TAX Export",path:"/workspace/export-tax"},{label:"Database Backup",path:"/workspace/backup"},{label:"Import Products",path:"/workspace/import-products"},{label:"Import Customers",path:"/workspace/import-customers"},{label:"Products Account Statements",path:"/workspace/product-statements"}]}];