import{useEffect,useState}from"react";import{inventory,org,products}from"../api";import{money}from"../utils";import{Page,Panel,Table,Field,Select}from"../components/common";
const emptyAdjustment={warehouseId:"",productId:"",variantId:"",quantity:"",unitCost:"",reason:""};
export default function Inventory(){const[rows,setRows]=useState([]),[warehouses,setWarehouses]=useState([]),[productList,setProductList]=useState([]),[warehouseId,setWarehouseId]=useState(""),[adjustment,setAdjustment]=useState(emptyAdjustment),[ledger,setLedger]=useState([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const selectedProduct=productList.find(x=>x.id===adjustment.productId);const variants=selectedProduct?.variants||[];
async function loadStock(id=warehouseId){setRows(await inventory.stock(id?{warehouseId:id}:{}))}
useEffect(()=>{org.warehouses().then(setWarehouses).catch(e=>setMessage(e.response?.data?.message||"Could not load warehouses"));products.list("").then(setProductList).catch(e=>setMessage(e.response?.data?.message||"Could not load products"));loadStock("").catch(e=>setMessage(e.response?.data?.message||"Could not load stock"))},[]);
function setField(key,value){setAdjustment(current=>({...current,[key]:value,...(key==="productId"?{variantId:""}:{})}))}
async function submitAdjustment(event){event.preventDefault();setBusy(true);setMessage("");try{await inventory.adjust({...adjustment,warehouseId:adjustment.warehouseId,variantId:adjustment.variantId||null,quantity:Number(adjustment.quantity),unitCost:Number(adjustment.unitCost)});setMessage("Stock adjustment saved.");setWarehouseId(adjustment.warehouseId);await loadStock(adjustment.warehouseId);const history=await inventory.ledger({warehouseId:adjustment.warehouseId,productId:adjustment.productId});setLedger(history);setAdjustment(current=>({...current,quantity:"",reason:""}))}catch(e){setMessage(e.response?.data?.message||"Stock adjustment failed")}finally{setBusy(false)}}
async function loadLedger(){if(!warehouseId)return;try{setLedger(await inventory.ledger({warehouseId}))}catch(e){setMessage(e.response?.data?.message||"Could not load stock history")}}
return <Page title="Stock Inventory" eyebrow="STOCK"><>{message&&<div className="notice">{message}<button onClick={()=>setMessage("")}>×</button></div>}<div className="two"><Panel title="Adjust Stock"><form className="formgrid" onSubmit={submitAdjustment}><Select label="Warehouse" value={adjustment.warehouseId} onChange={e=>setField("warehouseId",e.target.value)} required><option value="">Select warehouse</option>{warehouses.map(x=><option value={x.id} key={x.id}>{x.warehouseName}</option>)}</Select><Select label="Product" value={adjustment.productId} onChange={e=>setField("productId",e.target.value)} required><option value="">Select product</option>{productList.map(x=><option value={x.id} key={x.id}>{x.productCode} · {x.productName}</option>)}</Select>{variants.length>0&&<Select label="Variant" value={adjustment.variantId} onChange={e=>setField("variantId",e.target.value)}><option value="">Base product</option>{variants.map(x=><option value={x.id} key={x.id}>{x.variantCode} · {x.variantName}</option>)}</Select>}<Field label="Quantity change (+ in / - out)" type="number" step="0.001" value={adjustment.quantity} onChange={e=>setField("quantity",e.target.value)} required/><Field label="Unit cost" type="number" min="0" step="0.01" value={adjustment.unitCost} onChange={e=>setField("unitCost",e.target.value)} required/><Field label="Reason" value={adjustment.reason} onChange={e=>setField("reason",e.target.value)} required/><button className="primary" disabled={busy||!warehouses.length||!productList.length}>{busy?"Saving...":"Save adjustment"}</button></form></Panel><Panel title="Stock Balance" tools={<select value={warehouseId} onChange={e=>{setWarehouseId(e.target.value);loadStock(e.target.value)}}><option value="">All Warehouses</option>{warehouses.map(x=><option value={x.id} key={x.id}>{x.warehouseName}</option>)}</select>}><Table columns={[{key:"warehouse",label:"Warehouse"},{key:"code",label:"Code"},{key:"product",label:"Product"},{key:"quantity",label:"Qty"},{key:"averageCost",label:"Avg Cost",render:r=>money(r.averageCost)}]} rows={rows}/></Panel></div><Panel title="Stock Ledger" tools={<button onClick={loadLedger} disabled={!warehouseId}>Load history</button>}>{warehouseId?<Table columns={[{key:"transactionDate",label:"Date",render:r=>r.transactionDate?new Date(r.transactionDate).toLocaleString():"-"},{key:"transactionType",label:"Type"},{key:"referenceNo",label:"Reason / Reference"},{key:"quantityIn",label:"In"},{key:"quantityOut",label:"Out"},{key:"balanceAfter",label:"Balance"},{key:"unitCost",label:"Unit Cost",render:r=>money(r.unitCost)}]} rows={ledger}/>:<p className="empty">Select a warehouse to view its ledger.</p>}</Panel></></Page>}
